[project]
name = "101-alphas"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "duckdb>=1.4.2",
    "notebook>=7.5.0",
    "pandas>=2.3.3",
]
