[project]
name = "101-alphas"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "duckdb>=1.4.2",
    "notebook>=7.5.0",
    "pandas>=2.3.3",
    "streamlit>=1.32.0",
    "numpy>=1.26.0",
    "scipy>=1.12.0",
    "plotly>=5.19.0",
]
